import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import styles from "../styles/Home.module.css";

import Calvin from "../components/Calvin";
import Votr from "../components/Votr";
import CnC from "../components/CnC";
import Poly from "../components/Poly";
import Rosehill from "../components/Rosehill";
import Norman from "../components/Norman";
import Handful from "../components/Handful";

export default function Home() {
  const [isShownForma, setIsShownForma] = useState(false);
  const [isShownSkelter, setIsShownSkelter] = useState(false);
  const [isShownHina, setIsShownHina] = useState(false);
  const [isShownRoobert, setIsShownRoobert] = useState(false);
  const [isShownApple, setIsShownApple] = useState(false);
  const [isShownNudge, setIsShownNudge] = useState(false);
  const index = {
    forma: {
      yay: () => setIsShownForma(true),
      nay: () => setIsShownForma(false),
    },
    hina: {
      yay: () => setIsShownHina(true),
      nay: () => setIsShownHina(false),
    },
    skelter: {
      yay: () => setIsShownSkelter(true),
      nay: () => setIsShownSkelter(false),
    },
    roobert: {
      yay: () => setIsShownRoobert(true),
      nay: () => setIsShownRoobert(false),
    },
    apple: {
      yay: () => setIsShownApple(true),
      nay: () => setIsShownApple(false),
    },
    nudge: {
      yay: () => setIsShownNudge(true),
      nay: () => setIsShownNudge(false),
    },
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Will Andrée innit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Wmicon.png" />
      </Head>

      <main className={styles.main}>
        {isShownForma && (
          <div className="fontImage forma">
            <Image src="/FormaFont.png" alt="" width={267} height={75} />
          </div>
        )}
        {isShownHina && <span className="fontImage hina">Hina Mincho</span>}
        {isShownApple && (
          <span className="fontImage apple">Apple Garamond</span>
        )}
        {isShownSkelter && (
          <div className="fontImage skelter">
            <Image src="/SkelterFont.png" alt="" width={116} height={136} />
          </div>
        )}
        {isShownRoobert && (
          <div className="fontImage roobert">
            <Image src="/RoobertFont.png" alt="" width={471} height={100} />
          </div>
        )}

        {isShownNudge && (
          <div className="fontImage nudge">
            <Image src="/NudgeFont.svg" alt="" width={135} height={65} />
          </div>
        )}
        <div className="bigdiv">
          <div className="topBox">
            <span className="name">
              <Image
                src="/namespace.svg"
                alt="portfolio owner name logo"
                width={300}
                height={70}
              />
            </span>
            <hr />
            <div className="barkFloat">
              <Image src="/BarkPortDGreen.svg" alt="" width={200} height={79} />
            </div>

            <div className="arrow">
              <Image src="/arrow.png" alt="" width={200} height={200} />
            </div>
          </div>
          <div className="descripsh"></div>
        </div>
        <section className="bottomdiv">
          <Calvin />
          <CnC />
          <Votr />
          <Rosehill />
          <Poly />
          <Handful />
          <Norman />
          <hr />
        </section>
        <hr />
        <div className="descripsh descripsh--2">
          <div className="detailsContainer">
            <div>Hi, Barkley! Thank you for looking over some of my work.</div>
            <br />
            <div>
              {" "}
              If it{"'"}s possible to know someone by what they love, here are a
              few of my favorite artists/designers/firms →{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Timothy Luke
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Porto Rocha
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Haley Wollens
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Thibaud Allie
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Nick Sherman
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  James Harren
                </a>
              </Link>
              ,{" "}
              <Link href="https://tmthyl.uk/" passHref>
                <a target="_blank" rel="noopener noreferrer">
                  Austin Lee
                </a>
              </Link>
              ,{" "}
              <Link
                href="https://www.instagram.com/specialoffer.inc/?hl=en"
                passHref
              >
                <a target="_blank" rel="noopener noreferrer">
                  Special Offer, inc.
                </a>
              </Link>{" "}
              {"("}helmed by Brent David Frealy{")"},{" "}
              <Link
                href="https://www.instagram.com/specialoffer.inc/?hl=en"
                passHref
              >
                <a target="_blank" rel="noopener noreferrer">
                  Daniel Sannwald
                </a>
              </Link>
              ,{" "}
              <Link
                href="https://www.instagram.com/specialoffer.inc/?hl=en"
                passHref
              >
                <a target="_blank" rel="noopener noreferrer">
                  Daniel Swan
                </a>
              </Link>
              ,{" "}
              <Link
                href="https://www.instagram.com/specialoffer.inc/?hl=en"
                passHref
              >
                <a target="_blank" rel="noopener noreferrer">
                  Wiissa
                </a>
              </Link>
              , ...the list goes on and on.
            </div>
            <br />
            <div className="skillsContainer subcontainer">
              <h3 className="bskillz">skillz</h3>
              <ul>
                <li>Graphic Design</li>
                <li>User Experience Design</li>
                <li>Trend Forecasting</li>
                <li>Logo Design</li>
                <li>
                  Web Development <br />
                  <span>⬝ JavaScript</span>
                  <br />
                  <span>⬝ HTML/CSS</span>
                  <br />
                  <span>⬝ Sass</span>
                  <br />
                  <span>⬝ React</span>
                  <br />
                  <span>⬝ Express</span>
                  <br />
                  <span>⬝ Node</span>
                  <br />
                  <span>⬝ Wordpress Development</span>
                  <br />
                  <span>⬝ Git</span>
                </li>
              </ul>
            </div>
            <div className="businessContainer subcontainer">
              <div className="skillsContainer subcontainer">
                <h3 className="bskillz">tech</h3>
                <ul>
                  <li>Photoshop</li>
                  <li>Illustrator</li>
                  <li>Visual Studio</li>
                </ul>
              </div>
            </div>
            <div className="skillsContainer subcontainer">
              <h3 className="bskillz">Fonts I ❤</h3>
              <ul>
                <li
                  className="roobert font"
                  onMouseEnter={index.roobert.yay}
                  onMouseLeave={index.roobert.nay}
                >
                  Roobert
                </li>
                <li
                  className="america font"
                  onMouseEnter={index.hina.yay}
                  onMouseLeave={index.hina.nay}
                >
                  Hina Mincho
                </li>
                <li
                  className="skelter font"
                  onMouseEnter={index.skelter.yay}
                  onMouseLeave={index.skelter.nay}
                >
                  Skelter
                </li>
                <li
                  className="forma font"
                  onMouseEnter={index.forma.yay}
                  onMouseLeave={index.forma.nay}
                >
                  Forma
                </li>
                <li
                  className="forma font"
                  onMouseEnter={index.apple.yay}
                  onMouseLeave={index.apple.nay}
                >
                  Apple Garamond
                </li>
                <li
                  className="forma font"
                  onMouseEnter={index.nudge.yay}
                  onMouseLeave={index.nudge.nay}
                >
                  Nudge
                </li>
              </ul>
              <h3 className="bskillz" style={{ marginBlockStart: "1rem" }}>
                favorite designers
              </h3>
              <ul>
                <li>
                  <a href="http://tmthyl.uk/" target="_blank" rel="noreferrer">
                    Timothy Luke
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.instagram.com/d_a_n_i_e_l_s_w_a_n/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Daniel Swan
                  </a>
                </li>
              </ul>
            </div>
            <div className="businessContainer subcontainer">
              <h3 className="bskillz">business</h3>
              <ul>
                <li>
                  <a href="/resume" target="_blank">
                    Resumé
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/in/william-andree/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    LinkedIn
                  </a>
                </li>
                <li>
                  <a href="mailto:williamandree@gmail.com">
                    williamandree@gmail.com
                  </a>
                </li>
                <li>
                  <a href="tel:5738202616">(573) 820-2616</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
